# Accents
PRODUCT_PACKAGES += \
    AccentColorAmethystOverlay \
    AccentColorAquamarineOverlay \
    AccentColorBlackOverlay \
    AccentColorCarbonOverlay \
    AccentColorCinnamonOverlay \
    AccentColorGreenOverlay \
    AccentColorOceanOverlay \
    AccentColorOrchidOverlay \
    AccentColorPaletteOverlay \
    AccentColorPurpleOverlay \
    AccentColorSandOverlay \
    AccentColorSpaceOverlay \
    AccentColorTangerineOverlay \
    Amber \
    Blue \
    BlueGrey \
    Brown \
    Cyan \
    DeepOrange \
    DeepPurple \
    Green \
    Grey \
    Indigo \
    LightBlue \
    LightGreen \
    Lime \
    OhSoOrange \
    Orange \
    Pink \
    Purple \
    Red \
    Teal \
    Yellow
