# Accents
PRODUCT_PACKAGES += \
    AccentColorAmethystOverlay \
    AccentColorAquamarineOverlay \
    AccentColorBlackOverlay \
    AccentColorCarbonOverlay \
    AccentColorCinnamonOverlay \
    AccentColorGreenOverlay \
    AccentColorOceanOverlay \
    AccentColorOrchidOverlay \
    AccentColorPaletteOverlay \
    AccentColorPurpleOverlay \
    AccentColorSandOverlay \
    AccentColorSpaceOverlay \
    AccentColorTangerineOverlay \
    AccentColorAmberOverlay \
    AccentColorBlueOverlay \
    AccentColorBlueGreyOverlay \
    AccentColorBrownOverlay \
    AccentColorCyanOverlay \
    AccentColorDeepOrangeOverlay \
    AccentColorDeepPurpleOverlay \
    AccentColorGreenOverlay \
    AccentColorGreyOverlay \
    AccentColorIndigoOverlay \
    AccentColorLightBlueOverlay \
    AccentColorLightGreenOverlay \
    AccentColorLimeOverlay \
    AccentColorOhSoOrangeOverlay \
    AccentColorOrangeOverlay \
    AccentColorPinkOverlay \
    AccentColorPurpleOverlay \
    AccentColorRedOverlay \
    AccentColorTealOverlay \
    AccentColorYellowOverlay
